//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {

    
        public string FAC_NUMERO { get; set; }
        public string USU_DNI { get; set; }
        public string USU_NOMBRE { get; set; }
        public string USU_CORREO { get; set; }
        public string FAC_DIRECCION { get; set; }
        public string FAC_TELEFONO { get; set; }
        public System.DateTime FAC_FECHA { get; set; }
        public decimal FAC_TOTAL { get; set; }
        public string FAC_ESTADO { get; set; }
    

        public virtual USUARIO USUARIO { get; set; }
    }
}
