//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {

    
        public string PRD_ID { get; set; }
        public string PRD_NOMBRE { get; set; }
        public string PRD_DESC { get; set; }
        public string PRD_MARCA { get; set; }
        public decimal PRD_STOCK { get; set; }
        public decimal PRD_PRECIO { get; set; }
        public string PRD_IMAGEN { get; set; }
    

    }
}
